/* Cameron's menu data. Edit this file to change meals, toppings, sides, or prices.
   Prices: "est." = estimate for St. Pete-area stores, Oct 2026. Items with src:"A"/"P"/"AP"
   came from the store's online listing (aldi.us / delivery.publix.com) in Oct 2026; the rest are estimates. */
window.CAM = {
STORES:["Aldi","Publix","Walmart","Target","Trader Joe's","Winn-Dixie","Costco","Sam's Club"],

EQUIP:[
  {id:"foreman",label:"George Foreman grill",emoji:"🔥",featured:true},
  {id:"stove",label:"Stovetop",emoji:"🍳"},
  {id:"oven",label:"Oven",emoji:"♨️"},
  {id:"micro",label:"Microwave",emoji:"📟"},
  {id:"airfryer",label:"Air fryer",emoji:"💨"},
  {id:"slow",label:"Slow cooker",emoji:"🍲"},
  {id:"rice",label:"Rice cooker",emoji:"🍚"},
  {id:"sheet",label:"Sheet pan",emoji:"🟫"},
  {id:"skillet",label:"Skillet",emoji:"🍳"}
],

/* Burger toppings. v = variants (tap the chip to swap); first variant is the default. */
TOPPINGS:[
  {id:"patty",label:"Patty",v:["Beef patty (80/20)","Turkey patty","Chicken patty","Ground sirloin patty"]},
  {id:"bun",label:"Bun",v:["Sesame bun","Brioche bun","Potato bun","Pretzel bun","Plain white bun","Whole wheat bun","Lettuce wrap"]},
  {id:"cheese",label:"Cheese",v:["American cheese","Provolone","Muenster","Swiss","Cheddar","Pepper jack"]},
  {id:"lettuce",label:"Lettuce",v:["Iceberg lettuce","Romaine","Shredded lettuce"]},
  {id:"tomato",label:"Tomato"},
  {id:"onion",label:"Onion",v:["Raw white onion","Red onion","Grilled onions"]},
  {id:"pickles",label:"Pickles",v:["Dill chips","Dill spears","Bread & butter pickles"]},
  {id:"ketchup",label:"Ketchup"},
  {id:"mustard",label:"Mustard",v:["Yellow mustard","Spicy brown mustard","Honey mustard","Dijon mustard"]},
  {id:"mayo",label:"Mayo",v:["Mayo","Chipotle mayo","Garlic aioli"]},
  {id:"bacon",label:"Bacon",v:["Bacon","Turkey bacon"]},
  {id:"avocado",label:"Avocado",v:["Sliced avocado","Guacamole"]},
  {id:"jalapeno",label:"Jalapeños",v:["Pickled jalapeños","Fresh jalapeños"]},
  {id:"mushroom",label:"Mushrooms"},
  {id:"bbq",label:"BBQ sauce",v:["Sweet Baby Ray's BBQ","Honey BBQ","Kansas City BBQ","Carolina vinegar BBQ"]},
  {id:"egg",label:"Fried egg"},
  {id:"hot",label:"Hot sauce",v:["Frank's RedHot","Cholula","Tabasco","Sriracha","Texas Pete"]}
],

SIDES:["Potato chips","Fries","Fruit","Yogurt","Salad"],
DRILL:{
 "Potato chips":{emoji:"🥔",q:"Which chips?",opts:["Doritos","Lay's","Pringles","Ruffles","Cheetos","Kettle Brand"],
   sub:{"Doritos":["Nacho Cheese","Cool Ranch","Spicy Sweet Chili","Flamin' Hot"],"Lay's":["Classic","Sour Cream & Onion","BBQ","Salt & Vinegar"],"Pringles":["Original","Sour Cream & Onion","Cheddar Cheese","BBQ"],"Ruffles":["Original","Cheddar & Sour Cream","All Dressed"],"Cheetos":["Crunchy","Puffs","Flamin' Hot"],"Kettle Brand":["Sea Salt","Jalapeño","Salt & Vinegar","Honey Dijon"]}},
 "Fries":{emoji:"🍟",q:"Which fries?",opts:["Crinkle cut","Shoestring","Waffle","Curly","Steak fries","Sweet potato","Tots"]},
 "Fruit":{emoji:"🍎",q:"Which fruit?",opts:["Apples","Bananas","Grapes","Strawberries","Blueberries","Oranges","Watermelon","Pineapple"]},
 "Yogurt":{emoji:"🥣",q:"Which yogurt?",opts:["Chobani","Yoplait","Oikos","Dannon","Go-Gurt","Store brand"],
   sub:{"*":["Strawberry","Vanilla","Blueberry","Peach","Mixed berry","Plain"]}},
 "Salad":{emoji:"🥗",q:"Which salad?",opts:["Garden","Caesar","Spinach","Wedge"],
   then:{key:"Dressing",emoji:"🫙",q:"Which dressing?",opts:["Ranch","Italian","Caesar","Honey mustard","Balsamic","Blue cheese","Thousand Island"]}}
},

/* Meals for the Yes/No step. grill:true = Foreman-friendly. temp = USDA safe minimum. */
MEALS:[
 {id:"steak",emoji:"🥩",name:"Steak night",v:["Sirloin","Ribeye","NY strip","Flat iron","Chuck eye"],grill:true,
  time:"about 4–7 min (1-inch steak)",temp:"145°F + 3 min rest",
  grill:["Pat dry, salt + pepper or steak seasoning.","Preheat Foreman 5 min with the lid closed.","Lay steak on, close lid: about 4–7 min. Don't press down.","Check thickest part: 145°F, then rest 3 min before cutting."],
  stove:["Hot skillet, a little oil.","About 4–5 min per side for a 1-inch steak.","145°F, rest 3 min."]},
 {id:"burger",emoji:"🍔",name:"Burgers",grill:true,time:"about 4–6 min (⅓ lb patty)",temp:"160°F (ground beef)",
  grill:["Make ⅓ lb patties, thumb a dent in the middle.","Season both sides.","Foreman preheated, lid closed: about 4–6 min.","160°F in the middle. Cheese on for the last 30 sec."],
  stove:["Skillet medium-high.","About 4 min per side.","160°F in the middle."]},
 {id:"chicken",emoji:"🍗",name:"Grilled chicken breast",grill:true,time:"about 6–8 min (¾-inch thick)",temp:"165°F",
  grill:["Thick breast? Slice it in half sideways so it's even (¾ inch).","Oil + seasoning.","Foreman lid closed: about 6–8 min.","165°F in the thickest part. Rest 5 min so it stays juicy."],
  stove:["Skillet medium, a little oil.","About 5–7 min per side.","165°F."]},
 {id:"chixq",emoji:"🫓",name:"Chicken quesadilla / panini",v:["Quesadilla","Panini"],grill:true,time:"about 3–5 min",temp:"leftover chicken reheated to 165°F",
  grill:["Use leftover grilled chicken, sliced.","Tortilla (or 2 slices bread) + cheese + chicken.","Foreman = panini press: lid closed about 3–5 min till cheese melts.","Inside should be steaming hot (165°F)."],
  stove:["Skillet medium, no oil needed.","About 2–3 min per side till cheese melts."]},
 {id:"steakq",emoji:"🌮",name:"Steak quesadilla",grill:true,time:"about 3–4 min",temp:"leftover steak hot through",
  grill:["Slice leftover steak thin.","Tortilla + cheese + steak + salsa, fold.","Foreman lid closed about 3–4 min."],
  stove:["Skillet medium, about 2–3 min per side."]},
 {id:"stkegg",emoji:"🍳",name:"Steak & eggs",grill:true,time:"steak 1–2 min reheat · eggs 2–3 min",temp:"eggs till firm",
  grill:["Warm sliced leftover steak on the Foreman 1–2 min.","Eggs: skillet 2–3 min, or microwave scramble 1–1.5 min, stir halfway.","Cook eggs till no runny white."],
  stove:["Eggs in skillet 2–3 min; steak in the same pan 1–2 min."]},
 {id:"bowl",emoji:"🍚",name:"Chicken rice bowl",v:["Teriyaki","BBQ","Salsa + cheese","Plain"],grill:true,time:"about 6–8 min chicken · rice 90 sec",temp:"chicken 165°F",
  grill:["Grill chicken (or use leftovers), slice.","Rice: microwave pouch 90 sec, or rice cooker.","Rice + chicken + sauce + any grilled veggies."],
  stove:["Cook chicken in skillet 5–7 min per side, 165°F.","Rice + chicken + sauce."]},
 {id:"pork",emoji:"🐖",name:"Pork chops / country-style ribs",v:["Boneless pork chops","Country-style ribs (boneless)"],grill:true,time:"about 5–7 min (¾-inch chop)",temp:"145°F + 3 min rest",
  grill:["Season (BBQ rub or salt, pepper, garlic powder).","Foreman lid closed: chops about 5–7 min; thick country ribs about 8–12 min.","145°F, rest 3 min. Brush BBQ sauce on at the end."],
  stove:["Skillet medium-high, about 4–5 min per side.","145°F, rest 3 min."]},
 {id:"brats",emoji:"🌭",name:"Sausages / brats",v:["Brats","Italian sausage","Smoked sausage (pre-cooked)"],grill:true,time:"fresh about 10–14 min · pre-cooked about 5–6 min",temp:"fresh 160°F · pre-cooked just heat through",
  grill:["Poke? No, keep the skin whole so they stay juicy.","Foreman lid closed: fresh brats about 10–14 min.","Fresh: 160°F inside. Pre-cooked smoked sausage: about 5–6 min till hot."],
  stove:["Skillet medium, turn often, about 12–15 min.","160°F."]},
 {id:"veg",emoji:"🫑",name:"Grilled veggies (side)",v:["Zucchini & peppers","Onions & peppers","Mushrooms","Asparagus"],grill:true,time:"about 4–6 min",temp:"till tender",
  grill:["Slice ½-inch thick, toss with oil + salt.","Foreman lid closed about 4–6 min.","Done when soft with grill marks."],
  stove:["Skillet medium-high, about 6–8 min, stirring."]}
],

TIPS:{
 meat:[
  "Buy family / value packs: way cheaper per pound.",
  "Same day you shop: split into single portions in freezer bags.",
  "Write the date on every bag (Sharpie).",
  "Cooked leftovers: good 3–4 days in the fridge.",
  "Not eaten by day 4? Freeze it.",
  "Thaw overnight in the fridge, not on the counter.",
  "Cook once, eat 2–3 times: steak → steak plate → steak quesadilla → steak & egg bowl.",
  "Publix runs BOGO deals; Aldi is cheapest day-to-day on meat."
 ],
 temps:"Safe temps (USDA): steaks & pork chops 145°F + 3 min rest · burgers & ground meat 160°F · chicken 165°F · leftovers reheat to 165°F. A cheap instant-read thermometer (~$10–15) takes the guessing out."
},

/* Price catalog. a = Aldi est., p = Publix est. (null = not carried there).
   src: "A" Aldi online listing, "P" Publix online listing, "AP" both. aisle: meat, produce, dairy, bread, pantry, frozen, snacks */
PRICES:{
 chicken:{n:"Chicken breast, boneless skinless family pack",q:"~4 lb",aisle:"meat",a:9.62,p:22.12,src:"AP",hint:"Aldi listing $2.29/lb (Aldi says $1.99/lb in stores thru Nov 3) · Publix 4 lb+ pack $5.53/lb"},
 beef:{n:"Ground beef 80/20",q:"~2.25 lb pack (6 patties)",aisle:"meat",a:11.90,p:19.91,src:"AP",hint:"Aldi listing $5.29/lb · Publix listing $8.85/lb"},
 turkey:{n:"Ground turkey",q:"~2 lb",aisle:"meat",a:7.98,p:11.98},
 chickgr:{n:"Ground chicken",q:"~2 lb",aisle:"meat",a:7.98,p:11.98},
 sirloingr:{n:"Ground sirloin 90/10",q:"~2 lb",aisle:"meat",a:13.98,p:19.98},
 "steak:Sirloin":{n:"Top sirloin steak (2 steaks)",q:"~1.5 lb",aisle:"meat",a:14.99,p:18.29,src:"AP",hint:"Aldi listing $9.99/lb · Publix listing $12.19/lb"},
 "steak:Ribeye":{n:"Ribeye steak (2 steaks)",q:"~1.5 lb",aisle:"meat",a:20.99,p:25.49},
 "steak:NY strip":{n:"NY strip steak (2 steaks)",q:"~1.5 lb",aisle:"meat",a:19.49,p:23.99},
 "steak:Flat iron":{n:"Flat iron steak",q:"~1.5 lb",aisle:"meat",a:13.49,p:17.99},
 "steak:Chuck eye":{n:"Chuck eye steak",q:"~1.5 lb",aisle:"meat",a:11.99,p:14.99},
 "pork:Boneless pork chops":{n:"Boneless pork chops, family pack",q:"~2.5 lb (6 chops)",aisle:"meat",a:9.98,p:19.38,src:"AP",hint:"Aldi listing $3.99/lb · Publix listing $7.75/lb"},
 "pork:Country-style ribs (boneless)":{n:"Boneless country-style pork ribs",q:"~2.5 lb",aisle:"meat",a:8.73,p:12.48},
 "brats:Brats":{n:"Bratwurst",q:"1 pack (5–6)",aisle:"meat",a:2.69,p:8.75,src:"AP",hint:"Aldi Parkview 6 ct listing · Publix Johnsonville 5 ct listing"},
 "brats:Italian sausage":{n:"Italian sausage links",q:"1 pack (5)",aisle:"meat",a:3.99,p:6.99},
 "brats:Smoked sausage (pre-cooked)":{n:"Smoked sausage rope",q:"14 oz",aisle:"meat",a:2.99,p:4.99},
 bacon:{n:"Bacon",q:"12 oz",aisle:"meat",a:4.29,p:6.99},
 tbacon:{n:"Turkey bacon",q:"12 oz",aisle:"meat",a:2.99,p:4.99},
 eggs:{n:"Large eggs",q:"1 dozen",aisle:"dairy",a:1.85,p:2.19,src:"AP",hint:"Aldi Goldhen listing · Publix 12 ct listing"},
 cheeseslice:{n:"Sliced cheese",q:"1 pack",aisle:"dairy",a:2.49,p:4.29},
 shred:{n:"Shredded Mexican cheese",q:"8 oz",aisle:"dairy",a:2.29,p:3.49},
 yogurt:{n:"Yogurt cups",q:"6 cups",aisle:"dairy",a:3.30,p:6.00,hint:"Aldi price = Aldi's own brand"},
 lettuce:{n:"Lettuce",q:"1 head / bag",aisle:"produce",a:1.69,p:2.49},
 tomato:{n:"Tomatoes",q:"2",aisle:"produce",a:1.00,p:1.80},
 onion:{n:"Onions",q:"2",aisle:"produce",a:1.00,p:1.60},
 avocado:{n:"Avocados",q:"2",aisle:"produce",a:1.38,p:3.00},
 guac:{n:"Guacamole cups",q:"1 pack",aisle:"produce",a:3.49,p:4.99},
 jalfresh:{n:"Fresh jalapeños",q:"2",aisle:"produce",a:0.40,p:0.60},
 mushroom:{n:"Sliced mushrooms",q:"8 oz",aisle:"produce",a:1.79,p:2.99},
 "veg:Zucchini & peppers":{n:"Zucchini (2) + bell peppers (3 pk)",q:"for 3–4 sides",aisle:"produce",a:4.99,p:7.39},
 "veg:Onions & peppers":{n:"Bell peppers (3 pk) + 1 onion",q:"for 3–4 sides",aisle:"produce",a:3.99,p:5.79},
 "veg:Mushrooms":{n:"Whole mushrooms",q:"16 oz",aisle:"produce",a:2.99,p:4.99},
 "veg:Asparagus":{n:"Asparagus",q:"1 bunch",aisle:"produce",a:2.99,p:4.49},
 "Fruit:Apples":{n:"Apples",q:"3 lb bag",aisle:"produce",a:3.49,p:4.99},
 "Fruit:Bananas":{n:"Bananas",q:"~6",aisle:"produce",a:1.50,p:2.00},
 "Fruit:Grapes":{n:"Grapes",q:"~2 lb",aisle:"produce",a:3.98,p:5.98},
 "Fruit:Strawberries":{n:"Strawberries",q:"1 lb",aisle:"produce",a:2.49,p:3.99},
 "Fruit:Blueberries":{n:"Blueberries",q:"1 pint",aisle:"produce",a:2.99,p:4.49},
 "Fruit:Oranges":{n:"Oranges",q:"3 lb bag",aisle:"produce",a:3.99,p:5.49},
 "Fruit:Watermelon":{n:"Watermelon (cut, tub)",q:"1 tub",aisle:"produce",a:3.99,p:5.99},
 "Fruit:Pineapple":{n:"Pineapple",q:"1",aisle:"produce",a:1.99,p:3.49},
 "Salad:Garden":{n:"Garden salad bag",q:"1 bag",aisle:"produce",a:1.99,p:3.49},
 "Salad:Caesar":{n:"Caesar salad kit",q:"1 kit",aisle:"produce",a:2.99,p:4.49},
 "Salad:Spinach":{n:"Baby spinach",q:"1 bag",aisle:"produce",a:2.49,p:3.99},
 "Salad:Wedge":{n:"Iceberg head (wedge)",q:"1",aisle:"produce",a:1.69,p:2.49},
 dressing:{n:"Salad dressing",q:"1 bottle",aisle:"pantry",a:1.49,p:3.29},
 "bun:plain":{n:"Hamburger buns",q:"8 ct",aisle:"bread",a:1.55,p:4.41,src:"AP",hint:"Aldi L'oven Fresh listing · Publix Bakery 8 ct listing"},
 "bun:fancy":{n:"Buns",q:"4–8 ct",aisle:"bread",a:3.29,p:4.79},
 hotdogbun:{n:"Hot dog / brat buns",q:"8 ct",aisle:"bread",a:1.49,p:3.99},
 tortilla:{n:"Flour tortillas",q:"10 ct",aisle:"bread",a:1.99,p:3.29},
 bread:{n:"Sliced bread (panini/toast)",q:"1 loaf",aisle:"bread",a:1.49,p:3.29},
 ricepouch:{n:"Microwave rice pouches",q:"2",aisle:"pantry",a:2.58,p:3.98},
 ricebag:{n:"Long grain rice",q:"2 lb bag",aisle:"pantry",a:1.79,p:2.49},
 ketchup:{n:"Ketchup",q:"1 bottle",aisle:"pantry",a:1.89,p:3.49},
 mustard:{n:"Mustard",q:"1 bottle",aisle:"pantry",a:0.95,p:2.29},
 mayo:{n:"Mayo",q:"1 jar",aisle:"pantry",a:2.99,p:4.99},
 pickles:{n:"Pickles",q:"1 jar",aisle:"pantry",a:2.29,p:3.49},
 jalpickled:{n:"Pickled jalapeños",q:"1 jar",aisle:"pantry",a:1.79,p:2.69},
 bbq:{n:"BBQ sauce",q:"1 bottle",aisle:"pantry",a:1.49,p:2.99,hint:"Aldi price = Aldi's own brand"},
 hot:{n:"Hot sauce",q:"1 bottle",aisle:"pantry",a:1.29,p:2.99,hint:"Aldi price = Aldi's own brand"},
 salsa:{n:"Salsa",q:"1 jar",aisle:"pantry",a:1.99,p:3.49},
 teriyaki:{n:"Teriyaki sauce",q:"1 bottle",aisle:"pantry",a:1.99,p:3.49},
 season:{n:"Steak seasoning",q:"1 jar",aisle:"pantry",a:1.79,p:3.49},
 spray:{n:"Cooking spray",q:"1 can",aisle:"pantry",a:2.19,p:3.99},
 bags:{n:"Gallon freezer bags",q:"1 box",aisle:"pantry",a:2.49,p:4.49},
 fries:{n:"Frozen fries",q:"1 bag (~2 lb)",aisle:"frozen",a:2.49,p:3.99},
 chips:{n:"Chips",q:"1 bag",aisle:"snacks",a:2.19,p:5.49,hint:"Aldi price = Aldi's look-alike brand; Publix often has chips BOGO"},
 "chips:Pringles":{n:"Pringles",q:"1 can",aisle:"snacks",a:1.49,p:2.79,hint:"Aldi price = Aldi's look-alike stacked chips"},
 "chips:Kettle Brand":{n:"Kettle Brand chips",q:"1 bag",aisle:"snacks",a:null,p:4.79,hint:"Not carried at Aldi"}
},

SOURCES:[
 ["Aldi chicken breast family pack $2.29/lb","https://www.aldi.us/store/aldi/products/19554637-fresh-family-pack-chicken-breasts-per-lb"],
 ["Aldi ground beef 80/20 $5.29/lb","https://www.aldi.us/store/aldi/products/17771077-ground-beef-80-20-1-per-lb"],
 ["Aldi top sirloin $9.99/lb","https://www.aldi.us/store/aldi/products/17679795-beef-choice-black-angus-top-sirloin-steak-per-lb"],
 ["Aldi boneless pork chops $3.99/lb","https://www.aldi.us/store/aldi/products/20275650-boneless-center-cut-pork-chops-per-lb"],
 ["Aldi Parkview brats $2.69","https://www.aldi.us/store/aldi/products/19990802-parkview-stadium-bratwurst-14-oz"],
 ["Aldi eggs $1.85/dozen","https://www.aldi.us/store/aldi/products/115095-goldhen-grade-a-large-eggs-12-ct"],
 ["Aldi hamburger buns $1.55","https://www.aldi.us/store/aldi/products/20873280-l-oven-fresh-hamburger-buns-12-oz"],
 ["Publix chicken breast 4 lb+ $5.53/lb","https://delivery.publix.com/store/publix/products/387470-publix-chicken-all-natural-boneless-skinless-chicken-breast-per-lb"],
 ["Publix ground beef $8.85/lb","https://delivery.publix.com/store/publix/products/380937-publix-market-ground-beef-1-15-lb"],
 ["Publix top sirloin $12.19/lb","https://www.instacart.com/products/3175190-publix-premium-top-sirloin-steak-per-lb?retailerSlug=publix"],
 ["Publix boneless pork chops $7.75/lb","https://delivery.publix.com/store/publix/products/387970-publix-pork-all-natural-boneless-pork-loin-chops-1-55-lb"],
 ["Publix Johnsonville brats $8.75","https://delivery.publix.com/store/publix/products/16427623-johnsonville-sausage-original-holiday-promo-brats-82-grm"],
 ["Publix eggs 12 ct $2.19","https://delivery.publix.com/store/publix/products/324877-publix-eggs-large-12-ct"],
 ["Publix bakery buns 8 ct $4.41","https://delivery.publix.com/store/publix/products/321487-publix-original-hamburger-buns-8-ct"]
],

REPO:{name:"cameron-meals",url:"https://github.com/Burnsted/cameron-meals",site:"https://burnsted.github.io/cameron-meals/"}
};
